### ISSUE TITLE
Support updating metadata input forms for DataSpace

### ISSUE THREAD

**Issue by jrgriffiniii** [jrgriffiniii/dataspace-jspui#11]
The metadata input forms for item submissions need to be customized and updated on DataSpace (this was discussed during a sprint cycle meeting on 06/15/20).

**Comment by jrgriffiniii** [comment]
As noted by @matthewjchandler, these files are *not* stored within the JSPUI theme (please see https://wiki.lyrasis.org/display/DSDOC5x/Submission+User+Interface). Perhaps this issue should be transferred to https://github.com/pulibrary/princeton_ansible (as a part of #78)?

**Comment by kmcelwee** [comment]
This is being supported by https://github.com/PrincetonUniversityLibrary/dataspace/pull/1
