### ISSUE TITLE
Enable curators to add metadata to submitted items before approval for public release

### ISSUE THREAD

**Issue by matthewjchandler** [jrgriffiniii/dataspace-jspui#15]
I'm not sure if this is a configuration that can be changed, or something baked into DSpace. We curators often find ourselves needing to add metadata fields that are not shown to the submitter via the submission forms, and we can't do that unless we click "Approve" and then go back to edit metadata. Much of this will be rendered moot once the submission forms are updated, but still, it seems we should be able to add metadata before publishing if we need to.

**Comment by kmcelwee** [comment]
Reading around, this seems fundamental to dataspace, and we can't develop a workaround. As you say, once we finish https://github.com/PrincetonUniversityLibrary/dataspace/pull/1 this will hopefully be less an obstacle.
