### ISSUE TITLE
Change primary item identifier to DOI (if available)

### ISSUE THREAD

**Issue by matthewjchandler** [jrgriffiniii/dataspace-jspui#16]
On item pages, the ARK is given front-and-center with the message "Please use this identifier to cite or link to this item." Where DOIs are available, we want them to be used as the primary identifiers, and therefore given instead of ARKs at the top of item pages.

**Comment by kmcelwee** [comment]
duplication of https://github.com/pulibrary/dspace-development/issues/191, closing
