### ISSUE TITLE
Reconcile the Atmire GitLab branch for the About and Help page mockups with this repository

### ISSUE THREAD

**Issue by jrgriffiniii** [jrgriffiniii/dataspace-jspui#20]
This is an administrative issue which I must address in order to ensure that the work which was implemented for https://git.atmire.com/clients/princeton-5/-/tree/dataspace-jrg5-about-help can be squashed and prepared for a merge request (without falling further out of synchronization with this repository).

This branch should then be pushed to this repository, with the objective of reconciling the work being introduced in https://github.com/pulibrary/dataspace-jspui/pull/19 into this feature branch. Following this reconciliation, a second merge request will be issued against the Atmire GitLab code base for DataSpace.

**Comment by kmcelwee** [comment]
It was decided that the About and Help page should point directly to PRDS. This was addressed in https://github.com/pulibrary/dataspace-jspui/issues/3
