### ISSUE TITLE
Direct Help and About links to PRDS site

### ISSUE THREAD

**Issue by jrgriffiniii** [jrgriffiniii/dataspace-jspui#3]

**Comment by jrgriffiniii** [comment]
I'm rescoping this to include the deployment of these files into the production environment. Currently, I've needed to address Java compilation bugs (https://github.com/pulibrary/dataspace-jspui/compare/jspui-java-rewrite), and I am working to fully resolve these.

**Comment by jrgriffiniii** [comment]
Deploying this using Maven locally required the following updates:

https://github.com/pulibrary/dataspace-jspui/compare/docker-development2

Further, it was necessary to remove a static HTML file with `rm /dspace/webapps/jspui/index.html` (this was the static help page). Currently, the theme is rendered, but with the following errors:

![image](https://user-images.githubusercontent.com/1443986/85420736-9bd2b300-b541-11ea-88c9-e5c0c4df2803.png)

**Comment by jrgriffiniii** [comment]
I still need to improve the styling, but these have been uploaded:

![image](https://user-images.githubusercontent.com/1443986/95413450-781d5800-08f9-11eb-8f4a-4516bff8a48d.png)
![image](https://user-images.githubusercontent.com/1443986/95413497-9a16da80-08f9-11eb-95fc-503a3e9dc835.png)

**Comment by jrgriffiniii** [comment]
@matthewjchandler I apologize for the delays involved in addressing this, please find a preview for this on `dev` environment (which is restricted in access for the VPN) with https://dataspace-dev.princeton.edu/about and https://dataspace-dev.princeton.edu/help/index.html:

![image](https://user-images.githubusercontent.com/1443986/95592638-ed327f80-0a16-11eb-9b2f-c1de362ab1c7.png)
![image](https://user-images.githubusercontent.com/1443986/95592681-fb809b80-0a16-11eb-8499-dd9404e3d1ca.png)

**Comment by kmcelwee** [comment]
This content is being moved to the PRDS site. We will now point the "About" and "Help" tabs to the new PRDS pages. When PRDS has finished creating these pages, @matthewchandler will comment their links, and I will update the JSPUI to redirect the tabs to those links

**Comment by matthewjchandler** [comment]
The "About" page is already published on the PRDS site: https://researchdata.princeton.edu/research-lifecycle-guide/about-dataspace

**Comment by matthewjchandler** [comment]
The "Help" page is now published on the PRDS site: https://researchdata.princeton.edu/research-lifecycle-guide/dataspace-help

**Comment by kmcelwee** [comment]
File path:
```
princeton-5/dspace-jspui/src/main/webapp/layout/navbar-default.jsp
```

Decision log:
* use of `target=_blank`
* not deleting existing about and help html, only changing the links
* There are links to help text across dspace (via the question marks in circles, usually linking to a particular section of the help text). I'm  doing the main one just for now
